### ISSUE TITLE
R1.3: How to deploy an ontology service internally

### ISSUE THREAD

**Issue by nsjuty** [FAIRplus/FAIRPlus_squad1#3]
Fuqi & Eva
reviewer #1: @ereynrs 

doc: https://drive.google.com/open?id=1yPLs25w5OF7VMdiJXiomuwAs0J-Foq3L1LWhgh94iw0
note: recipe on how to deploy each service identified in R1.1 locally

**Comment by FuqiX** [comment]
@EvaMart

**Comment by FuqiX** [comment]
Link to recipe: https://hackmd.io/@7GH6ArIbRnm_7fgcv8mmWw/H1axYY3wU/edit

**Comment by emilianoreynares** [comment]
As a reviewer, I added comments to the markdown version of the recipe.

**Comment by FuqiX** [comment]
Thanks a lot for your nice suggestions. @ereynrs Could you please also add yourself as a reviewer in the "author" section?

 I've added them as TODOs in the recipe. @EvaMart and I will revise the recipe and provide an updated version once we finished.

**Comment by emilianoreynares** [comment]
Recipe done. Ready to be pushed to the Cookbook.

**Comment by FuqiX** [comment]
Pushed to cookbook dev https://github.com/FAIRplus/the-fair-cookbook/blob/dev/docs/content/recipes/infrastructure/UC3_R13_local_ontology_services.md @nsjuty I'll close this ticket

**Comment by nsjuty** [comment]
thanks @FuqiX
