### ISSUE TITLE
R2.2.1: (self) request terms to be added to a public ontology

### ISSUE THREAD

**Issue by nsjuty** [FAIRplus/FAIRPlus_squad1#7]
Ulrich & Emma
reviewer #1: @nsjuty 

doc: https://docs.google.com/document/d/1sq73y2vF0yhJ8M4xGd4tR5uwzSV1pOptcte5pKSyi7U/edit#heading=h.xoq2y4kj3obq

Identify 3-5 public ontologies, describe how to request new terms

**Comment by EmV25** [comment]
Recipe in markdown:
https://hackmd.io/@FAIRplus-Ulrich-Emma/H15DOXQd8

**Comment by proccaserra** [comment]
@EmV25 I am getting a permission denied (403) . Would mind granting me access? thx.

**Comment by EmV25** [comment]
@proccaserra Sorry for the inconvenience! I changed the permission and send you an invite, hope it works now.

**Comment by nsjuty** [comment]
21/04/20
Review of markdown version of R2.2.1 (https://hackmd.io/@FAIRplus-Ulrich-Emma/H15DOXQd8)
reviewer: Nick Juty

CATCULT criteria summary:

Coverage/comprehensivenes:See notes below - seems comprehensive
Assumptions: basic knowledge of ontologies
Transferable (can it be used for other data): no 

comprehensible/grammar: well written and understandable
Uses markdown: yes
Layout: logical, well structured, nagivable
Tested: no

Comments:

General: add the recipe id somewhere, and the link to GitHub to allow inter-links
md graphical overview broken?
Where possible, please lso indicate 'who' can request a term (some it is anyone, some it is member, and for those using GH, you will need a GH account, can give a link to that)


specific comments:
logical definition: suggest parent terms -> parent and child terms (where in the tree)

SNOMED: "Requests can be submitted by members "
- what about if you are no a member of ...
RxNorm: NLM support and 'form' links are broken

**Comment by nsjuty** [comment]
to confirm, that was all the comments I had @EmV25 @proccaserra

**Comment by ulo** [comment]
@nsjuty thank you for the feedback! we will update the recipe until next week.
I could not assign myself to the issue (which I could in the FAIRPlus_squad2 project). Could you maybe add me as collaborator to the FAIRPlus_squad1 project?

**Comment by ulo** [comment]
Dear Nick, thanks for the great review!
Below some point-by-point response to the feedback:

>  
> General: add the recipe id somewhere, and the link to GitHub to allow inter-links

Emma added the recipe ID to the title.

But I am not sure which link to GitHub you want?
To the cookbook? https://github.com/FAIRplus/the-fair-cookbook
Or to this issue? https://github.com/FAIRplus/FAIRPlus_squad1/issues/7

> md graphical overview broken?

I do not think that mermaid syntax will work within hackmd.io, or does it?
It works in the [mermaid live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggTFJcbiAgICBBKHRhcmdldCA8YnI-IG9udG9sb2d5KSAtLT4gQltpZGVudGlmeSA8YnI-IG1pc3NpbmcgdGVybV1cbiAgICBCIC0tPiBDKGRlc2NyaXB0aW9uIG9mIDxicj4gcmVxdWVzdGVkIHRlcm0pXG4gICAgQyAtLT4gRHtpZGVudGlmeSA8YnI-IHJlcXVlc3QgPGJyPiBwcm9jZXNzfVxuICAgIEEgLS0-IERcbiAgICBEIC0tPnxmb3JtYWwgPGJyPiBwcm9jZXNzfCBFW2ZvbGxvdyA8YnI-IGd1aWRlbGluZXNdXG4gICAgRCAtLT58R2l0aHViIHdpdGggPGJyPiBleHBsaWNpdCBndWlkZWxpbmVzfCBGW3Bvc3QgR2l0SHViIGlzc3VlIDxicj4gZm9sbG93aW5nIGd1aWRlbGluZXNdXG4gICAgRCAtLT58R2l0aHViIHdpdGhvdXQgPGJyPiBndWlkZWxpbmVzfCBHW3Bvc3QgR2l0SHViIGlzc3VlXVxuICAgIEQgLS0-fGVtYWlsfCBIW3dyaXRlIGVtYWlsIHRvIDxicj4gZWRpdG9yL293bmVyXVxuICAgIEUgLS0-IEl7ZGVjaXNpb24gPGJyPiBvbiByZXF1ZXN0fVxuICAgIEYgLS0-IElcbiAgICBHIC0tPiBJXG4gICAgSCAtLT4gSVxuICAgIEkgLS0-fHBvc2l0aXZlfCBKW3VzZSBuZXcgdGVybV1cbiAgICBJIC0tPnxuZWdhdGl2ZXwgS1tmaW5kIGFsdGVybmF0aXZlXSIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19).

> Where possible, please also indicate 'who' can request a term (some it is anyone, some it is member, and for those using GH, you will need a GH account, can give a link to that)

I added a paragraph on this in the initial section ("Background")

> 
> specific comments:
> logical definition: suggest parent terms -> parent and child terms (where in the tree)

"child terms" added to the logical definition

> 
> SNOMED: "Requests can be submitted by members "
> 
>     * what about if you are no a member of ...

This is something we did not covered so far. I am not sure that we can give some general statements here...
**Also we did not cover yet what would happen if a request is declined.** The obvious alternative would be to use a modified/extended in-house version of this ontology (is there a recipe on this that we could refer to?).

>       RxNorm: NLM support and 'form' links are broken

All links are double-checked now.

**Comment by EmV25** [comment]
> * what about if you are no a member of ...

I added a few lines on this.

Some potential final to do's:
- [ ] Add user story
- [ ] Add CMM table
- [ ] Fix diagram (Mermaid works - markdown or HackMD issue?)
- [ ] Align recipe outline with other recipes (?)

**Comment by nsjuty** [comment]
discussed in squad call. changes look good:
decided to:
- add CMM table as is in the template
- strategies to address issues with mermaid/md discussed, hopefully that works..

**Comment by nsjuty** [comment]
completed:
https://fairplus.github.io./cookbook-dev/recipes/interoperability/ontology-new-term-request-recipe.html

**Comment by nsjuty** [comment]
complete:
https://fairplus.github.io./cookbook-dev/recipes/infrastructure/UC3_R13_local_ontology_services.html
