### ISSUE TITLE
R4: How to build an application ontology with ROBOT

### ISSUE THREAD

**Issue by nsjuty** [FAIRplus/FAIRPlus_squad1#9]
Fuqi, Dani & Emiliano
reviewer #1: @proccaserra 

doc:

Tasks in building and maintaining an application ontology include,generating subsets, QC, generating release files, etc. ROBOT provides many command covering these tasks. An example showing how to build an application ontology would be nice. 
1. What are the tasks for building and maintaining ontologies.
2. how to use ROBOT for these tasks
3. provide an example

**Comment by emilianoreynares** [comment]
Feedback from FAIRplus Cookbook Call & Rolling notes.
Group will look into where the derived recipes would fit best in the Table of Content -- responsible: @ereynrs

**Comment by ereynrs** [comment]
Notes on the drafting of a first version of the app ontology can be found in https://hackmd.io/@ereynrs/rJLiTd5cU

**Comment by nsjuty** [comment]
submit the recipe as is, worry about a next version with use case specific modifications  after submission. 
laurent.winckers@maastrichtuniversity.nl can review

**Comment by ereynrs** [comment]
Following the recipe, two versions of an app ontology has been developed for a specific use case.

Dev notes: https://github.com/FAIRplus/the-fair-cookbook/blob/ontology_robot_recipe/docs/content/recipes/ontology-robot/R4%20notes.md

Dev Artifacts (dataset, seed files, jupyter notebooks, branches extracted, robot templates, and obtained app ontologies):  https://drive.google.com/drive/u/1/folders/1kY_oBDJvs901vNS_NKM7EFoozIXlWK9k

**Comment by FuqiX** [comment]
- Master docs:
D1: [Recipe in HackMD, live version](https://hackmd.io/6AGo6ZdeTlyGRqv_tFGtuA) :bulb: Please edit this doc
D2: [Recipe in Cookbook github](https://github.com/FAIRplus/the-fair-cookbook/blob/ontology_robot_recipe/docs/content/recipes/ontology-robot-recipe.md)  D1 will be pushed to here.

- Other docs:
D3: [ Karsten - First draft of use-case CQs](https://github.com/karsten-quast/the-fair-cookbook/blob/ontology_robot_recipe/docs/content/recipes/ontology-robot-recipe.md)
D4: [Emiliano - Notes on the drafting of a first version of the app ontology](https://hackmd.io/@ereynrs/rJLiTd5cU)
D5: [Emiliano - Notes pushed to the ontology_robot_recipe branch](https://github.com/FAIRplus/the-fair-cookbook/blob/ontology_robot_recipe/docs/content/recipes/ontology-robot/R4%20notes.md)
D6: [Emiliano - Dev notes](https://github.com/FAIRplus/the-fair-cookbook/blob/ontology_robot_recipe/docs/content/recipes/ontology-robot/R4%20notes.md)
D7: [Emiliano - Dev Artifacts (dataset, seed files, jupyter notebooks, branches extracted, robot templates, and obtained app ontologies)](https://drive.google.com/drive/u/1/folders/1kY_oBDJvs901vNS_NKM7EFoozIXlWK9k)

_D3-7 will be merged/extracted to D1._

**Comment by emilianoreynares** [comment]
PR on the-fair-cookbook dev branch.
